# docker/docker-compose.yml
version: '3'

services:
  php-fpm:
    restart: unless-stopped
    build:
      context: ./docker/php-fpm
    # add health-check here
    networks:
      - no-internet
      - internet
    environment:
      - APP_ENV=dev
      - APP_SECRET=efd9cc33888c22ee608250719061d197
    volumes:
      - ./:/var/www/product
  nginx:
    restart: unless-stopped
    image: nginx:1.21.4-alpine
    networks:
      - no-internet
      - internet
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./:/var/www/product
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/log:/var/log
      - ./docker/nginx/common:/etc/nginx/common
    environment:
      PRODUCT_API_PORT: 8080
      NGINX_SERVER_NAME: localhost
    depends_on:
      - php-fpm
      - mysql
  mysql:
    restart: unless-stopped
    image: mysql:8
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - no-internet
    volumes:
      - ./var/data/mysql:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      # - "--innodb-use-native-aio=0"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
      MYSQL_USER: test
      MYSQL_PASSWORD: test

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
